### PR TITLE
Text edit function, /alter2 command using said function

### PR DESCRIPTION
**Pull request by KennethSamael**
Couldn't think of a better name for the command. Could maybe have stolen /alter command and merged the original command into this, as an "rewrite all" option, but not sure how much people would like needing an extra step if they use it a lot.

I've probably spent more effort on this than I should, but it feels really good to use when I'm testing it out. Makes it so easy to tweak the AI's responses, like removing a sentence that ruins an otherwise good response, or editing some part where the AI gets confused about who is doing what. And you don't lose your linebreaks! Only part I'm slightly dissatisfied is how many sentences you end up with when the dialogue starts spamming you with very short dialogue, like here:

> A voice calls back. "I am a tree".
> "Are you a tree?" You ask.
> "Yes I am. Are you?"
> "No, I'm not a tree".

> 0) A voice calls back.
> 1) "I am a tree".
> 2) "Are you a tree?"
> 3) You ask.
> 4) "Yes I am.
> 5) Are you?"
> 6) "No, I'm not a tree".

But it probably can't be helped.

Oh, and it also lets you edit `story_start` when there's no result to edit, not sure why the original /alter command didn't do that.

### CODE REVIEW

**Comment by marktaiwan** [comment]
I think it would be cleaner to add a "Rewrite all" option to `string_edit`, and replace the existing `/alter` command. At least that would be my personal preference.

And the `string_to_sentence_list` function looks really nice too, and I wonder if #21 and #23 can benefit from the more accurate sentence splitting.

**Comment by thadunge2** [comment]
Yeah, I think it's getting a bit silly to be having multiple versions of each command, personally.

**Comment by KennethSamael** [comment]
There, I merged /context with /editcontext, and /alter with /alter2. Also added a few more tweaks.

**Comment by thadunge2** [comment]
Well done.

**Pull request merged**
