### PR TITLE
Allow changing story memory

### PR DESCRIPTION
**Pull request by ShnitzelKiller**
Add the length of memory (how many actions the generator looks back at) as a parameter that can be changed at the start of a new game, at runtime with /memory, and is saved and loaded with each story.

### CODE REVIEW

**Comment by thadunge2** [comment]
Gonna have to say I probably would not merge this one. Story memory is already much higher than GPT-2's ability to take in the story's history, and in longer games most of it is automatically trimmed off to prevent the game from crashing. This would be a pretty pointless option to change IMHO.

**Comment by ShnitzelKiller** [comment]
Story memory can be decreased, then. How about removing it from the main settings prompt but leaving it in the commands?

**Comment by thadunge2** [comment]
If you can make a case for it, maybe, but otherwise it's just instructions clutter that will confuse anons and have no noticeable (positive) effect on their results, IMHO.

**Comment by ShnitzelKiller** [comment]
Sure, I can see that. I just have an aversion to hardcoded constants, especially when they're repeated in the code, so I tried making it a parameter just in case.

**Pull request closed without merging**
