### PR TITLE
Update play.py

### PR DESCRIPTION
**Pull request by AIDungeonpastes**

### CODE REVIEW

**Comment by marktaiwan** [comment]
Maybe you could be more descriptive as to what this patch does? It looks like a command to alter the latest generated result.

There are a few things to note:
- You need to add the new command to the `def instructions()` with explanations on what it does.
- The `!` command already replaces `\n` with a line break:
https://github.com/thadunge2/AIDungeon/blob/21c56cc7ee7487462ff7ec89f284043242d4720d/play.py#L348-L349
Doing it differently here now will only serve to confuse the players.
- The game automatically insert line breaks at certain widths. On a terminal the extra line breaks makes it more difficult for players to copy and paste the output for editing. Maybe add something like:
```
AIDungeon2 thinks what happened was:
[print unformatted story_manager.story.results[-1]

Write what really happened:
```

**Comment by thadunge2** [comment]
Write a description for it in the instructions and I'll pull it.

**Comment by marktaiwan** [comment]
@thadunge2 
It appears no further changes are forthcoming from #9 and #10, I'll work on this feature with the aforementioned changes added in, if that's okay with you?

**Comment by thadunge2** [comment]
Update it for the latest changes and add the command to the instructions.

**Pull request closed without merging**
