### PR TITLE
Alter Command

### PR DESCRIPTION
**Pull request by PapayasTehSkeletor**
This works fine, no more black hooded figures and random sleeps!

### CODE REVIEW

**Comment by marktaiwan** [comment]
It's functionally identical to #9

**Comment by PapayasTehSkeletor** [comment]
Oh, right, sorry.

**Comment by thadunge2** [comment]
This one doesn't add it to the instructions either.

**Comment by thadunge2** [comment]
Update it for the latest changes and add the command to the instructions.

**Pull request closed without merging**
